"""Add TableReservation model

Revision ID: 01ab925519bf
Revises: fcd300bf9fc6
Create Date: 2026-07-04 16:32:28.651275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ab925519bf'
down_revision: Union[str, Sequence[str], None] = 'fcd300bf9fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_reservations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('reservation_time', sa.DateTime(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('table_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_reservations_reservation_time'), 'table_reservations', ['reservation_time'], unique=False)
    op.create_index(op.f('ix_table_reservations_status'), 'table_reservations', ['status'], unique=False)
    op.create_index(op.f('ix_table_reservations_table_id'), 'table_reservations', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_reservations_table_id'), table_name='table_reservations')
    op.drop_index(op.f('ix_table_reservations_status'), table_name='table_reservations')
    op.drop_index(op.f('ix_table_reservations_reservation_time'), table_name='table_reservations')
    op.drop_table('table_reservations')
    # ### end Alembic commands ###
