"""Add is_spicy_customizable

Revision ID: 0e10258b03ae
Revises: b1ec273bbaab
Create Date: 2026-07-29 12:11:44.202237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e10258b03ae'
down_revision: Union[str, Sequence[str], None] = 'b1ec273bbaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_categories', sa.Column('is_spicy_customizable', sa.Boolean(), nullable=False))
    op.add_column('menu_items', sa.Column('is_spicy_customizable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'is_spicy_customizable')
    op.drop_column('menu_categories', 'is_spicy_customizable')
    # ### end Alembic commands ###
