"""Add employee_attendance table

Revision ID: 0fa6be22fc05
Revises: 22fa6d74f6cb
Create Date: 2026-08-03 16:02:14.199424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fa6be22fc05'
down_revision: Union[str, Sequence[str], None] = '22fa6d74f6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_attendance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_attendance_date'), 'employee_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_employee_attendance_employee_id'), 'employee_attendance', ['employee_id'], unique=False)
    op.drop_column('employees', 'attendance_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('attendance_status', mysql.VARCHAR(length=20), nullable=True))
    op.drop_index(op.f('ix_employee_attendance_employee_id'), table_name='employee_attendance')
    op.drop_index(op.f('ix_employee_attendance_date'), table_name='employee_attendance')
    op.drop_table('employee_attendance')
    # ### end Alembic commands ###
