"""Add image_url to MenuCategory

Revision ID: 1a9a60f9ee6b
Revises: 0e10258b03ae
Create Date: 2026-07-29 12:37:41.233281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9a60f9ee6b'
down_revision: Union[str, Sequence[str], None] = '0e10258b03ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_categories', 'image_url')
    # ### end Alembic commands ###
