"""add_session_pin

Revision ID: 1bf7feaab08d
Revises: f7962851bca4
Create Date: 2026-08-18 14:50:08.239932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf7feaab08d'
down_revision: Union[str, Sequence[str], None] = 'f7962851bca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_sessions', sa.Column('session_pin', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_sessions', 'session_pin')
    # ### end Alembic commands ###
