"""Add Kitchen KDS

Revision ID: 209895a48a49
Revises: 9763c26d2293
Create Date: 2026-07-23 06:05:09.228819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209895a48a49'
down_revision: Union[str, Sequence[str], None] = '9763c26d2293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchens_name'), 'kitchens', ['name'], unique=True)
    op.add_column('employees', sa.Column('kitchen_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_employees_kitchen_id'), 'employees', ['kitchen_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'kitchens', ['kitchen_id'], ['id'], ondelete='SET NULL')
    op.add_column('menu_items', sa.Column('kitchen_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_menu_items_kitchen_id'), 'menu_items', ['kitchen_id'], unique=False)
    op.create_foreign_key(None, 'menu_items', 'kitchens', ['kitchen_id'], ['id'], ondelete='SET NULL')
    op.add_column('order_items', sa.Column('status', sa.String(length=20), server_default='received', nullable=False))
    op.create_index(op.f('ix_order_items_status'), 'order_items', ['status'], unique=False)
    
    # --- Custom Data Migration ---
    connection = op.get_bind()
    connection.execute(sa.text("INSERT INTO kitchens (name, description, is_active, created_at, updated_at) VALUES ('Main Kitchen', 'Default kitchen', 1, now(), now())"))
    # Assign existing menu items and employees to the new kitchen
    connection.execute(sa.text("""
        UPDATE menu_items 
        SET kitchen_id = (SELECT id FROM kitchens WHERE name = 'Main Kitchen' LIMIT 1)
    """))
    connection.execute(sa.text("""
        UPDATE employees 
        SET kitchen_id = (SELECT id FROM kitchens WHERE name = 'Main Kitchen' LIMIT 1)
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_status'), table_name='order_items')
    op.drop_column('order_items', 'status')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_index(op.f('ix_menu_items_kitchen_id'), table_name='menu_items')
    op.drop_column('menu_items', 'kitchen_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_kitchen_id'), table_name='employees')
    op.drop_column('employees', 'kitchen_id')
    op.drop_index(op.f('ix_kitchens_name'), table_name='kitchens')
    op.drop_table('kitchens')
    # ### end Alembic commands ###
