"""add is_active to menuitem

Revision ID: 227bb7957080
Revises: f1471c7fa676
Create Date: 2026-07-04 14:26:31.735501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227bb7957080'
down_revision: Union[str, Sequence[str], None] = 'f1471c7fa676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'is_active')
    # ### end Alembic commands ###
