"""Add attendance_status to Employee

Revision ID: 22fa6d74f6cb
Revises: 7505c813afe7
Create Date: 2026-08-03 15:52:00.897772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fa6d74f6cb'
down_revision: Union[str, Sequence[str], None] = '7505c813afe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('attendance_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'attendance_status')
    # ### end Alembic commands ###
