"""Add order_type to Order

Revision ID: 2c53d017058e
Revises: 01ab925519bf
Create Date: 2026-07-08 16:23:07.546002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c53d017058e'
down_revision: Union[str, Sequence[str], None] = '01ab925519bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_orders_order_type'), 'orders', ['order_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_type'), table_name='orders')
    op.drop_column('orders', 'order_type')
    # ### end Alembic commands ###
