"""Add section to Employee

Revision ID: 3f6192ecb6c5
Revises: b152bc29f8be
Create Date: 2026-08-06 15:42:17.060296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6192ecb6c5'
down_revision: Union[str, Sequence[str], None] = 'b152bc29f8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('section', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'section')
    # ### end Alembic commands ###
