"""Add break tracking to employees

Revision ID: 70b5a61ec212
Revises: 0fa6be22fc05
Create Date: 2026-08-03 16:27:56.448981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b5a61ec212'
down_revision: Union[str, Sequence[str], None] = '0fa6be22fc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_on_break', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('break_cover_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'break_cover_data')
    op.drop_column('employees', 'is_on_break')
    # ### end Alembic commands ###
