"""Add gender to Employee

Revision ID: 7505c813afe7
Revises: 1a9a60f9ee6b
Create Date: 2026-08-03 15:39:05.391774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7505c813afe7'
down_revision: Union[str, Sequence[str], None] = '1a9a60f9ee6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'gender')
    # ### end Alembic commands ###
