"""add virtual tables for merging

Revision ID: 7678dec6966c
Revises: 235ac31603b1
Create Date: 2026-07-20 16:37:39.341851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7678dec6966c'
down_revision: Union[str, Sequence[str], None] = '235ac31603b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_tables', sa.Column('is_virtual', sa.Boolean(), nullable=False))
    op.add_column('restaurant_tables', sa.Column('parent_table_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_restaurant_tables_parent_table_id'), 'restaurant_tables', ['parent_table_id'], unique=False)
    op.create_foreign_key(None, 'restaurant_tables', 'restaurant_tables', ['parent_table_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_tables', type_='foreignkey')
    op.drop_index(op.f('ix_restaurant_tables_parent_table_id'), table_name='restaurant_tables')
    op.drop_column('restaurant_tables', 'parent_table_id')
    op.drop_column('restaurant_tables', 'is_virtual')
    # ### end Alembic commands ###
