"""Add reviews tables

Revision ID: 9763c26d2293
Revises: 06f8f2d24b32
Create Date: 2026-07-22 16:29:48.655216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9763c26d2293'
down_revision: Union[str, Sequence[str], None] = '06f8f2d24b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_session_id'), 'reviews', ['session_id'], unique=False)
    op.create_table('item_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_item_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_reviews_menu_item_id'), 'item_reviews', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_item_reviews_review_id'), 'item_reviews', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_reviews_review_id'), table_name='item_reviews')
    op.drop_index(op.f('ix_item_reviews_menu_item_id'), table_name='item_reviews')
    op.drop_table('item_reviews')
    op.drop_index(op.f('ix_reviews_session_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
