"""Add AssistanceRequest model

Revision ID: b0bd1d40b022
Revises: 24f2d311205b
Create Date: 2026-07-21 15:44:19.865268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bd1d40b022'
down_revision: Union[str, Sequence[str], None] = '24f2d311205b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistance_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistance_requests_request_type'), 'assistance_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_assistance_requests_resolved_by_employee_id'), 'assistance_requests', ['resolved_by_employee_id'], unique=False)
    op.create_index(op.f('ix_assistance_requests_session_id'), 'assistance_requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_assistance_requests_status'), 'assistance_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistance_requests_status'), table_name='assistance_requests')
    op.drop_index(op.f('ix_assistance_requests_session_id'), table_name='assistance_requests')
    op.drop_index(op.f('ix_assistance_requests_resolved_by_employee_id'), table_name='assistance_requests')
    op.drop_index(op.f('ix_assistance_requests_request_type'), table_name='assistance_requests')
    op.drop_table('assistance_requests')
    # ### end Alembic commands ###
