"""add_token_number_to_order

Revision ID: b152bc29f8be
Revises: fe7c25bc1aed
Create Date: 2026-08-04 14:23:51.900727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b152bc29f8be'
down_revision: Union[str, Sequence[str], None] = 'fe7c25bc1aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('token_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_orders_token_number'), 'orders', ['token_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_token_number'), table_name='orders')
    op.drop_column('orders', 'token_number')
    # ### end Alembic commands ###
