"""add x_position and y_position to tables

Revision ID: b1ec273bbaab
Revises: 04c25da41252
Create Date: 2026-07-28 14:06:34.873225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ec273bbaab'
down_revision: Union[str, Sequence[str], None] = '04c25da41252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_tables', sa.Column('x_position', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('restaurant_tables', sa.Column('y_position', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_tables', 'y_position')
    op.drop_column('restaurant_tables', 'x_position')
    # ### end Alembic commands ###
