"""add_bill_requested_to_customer_session

Revision ID: d14e77f8fa4b
Revises: 38c11eca5bf8
Create Date: 2026-07-20 15:12:15.402011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14e77f8fa4b'
down_revision: Union[str, Sequence[str], None] = '38c11eca5bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_sessions', sa.Column('bill_requested', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_sessions', 'bill_requested')
    # ### end Alembic commands ###
