"""Add employee document urls

Revision ID: f7962851bca4
Revises: 3f6192ecb6c5
Create Date: 2026-08-10 13:02:32.476454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7962851bca4'
down_revision: Union[str, Sequence[str], None] = '3f6192ecb6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('aadhar_url', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('pan_url', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('passbook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'passbook_url')
    op.drop_column('employees', 'pan_url')
    op.drop_column('employees', 'aadhar_url')
    # ### end Alembic commands ###
