"""add name and floor to tables

Revision ID: fcd300bf9fc6
Revises: 2334164f7883
Create Date: 2026-07-04 15:58:24.517150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd300bf9fc6'
down_revision: Union[str, Sequence[str], None] = '2334164f7883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_tables', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('restaurant_tables', sa.Column('floor', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_tables', 'floor')
    op.drop_column('restaurant_tables', 'name')
    # ### end Alembic commands ###
